export const Actions = {
    USER: {
        SET_AUTHENTICATED: "USER.SET_AUTHENTICATED",
        SET_UNAUTHENTICATED: "USER.SET_UNAUTHENTICATED",
        SET_USER: "USER.SET_USER",
        LOADING_USER: "USER.LOADING_USER",
        STOP_LOADING_USER: "USER.STOP_LOADING_USER"
    },
    UI: {
        SET_ERRORS: "UI.SET_ERRORS",
        CLEAR_ERRORS: "UI.CLEAR_ERRORS",
        SET_ACTION_DONE: "UI.SET_ACTION_DONE",
        CLEAR_ACTION: "UI.CLEAR_ACTION",
        SEND_EMAIL: "UI.SEND_EMAIL",
        STOP_SEND_EMAIL: "UI.STOP_SEND_EMAIL"
    }
};