export const Actions = {
    USER: {
        SET_AUTHENTICATED: "USER.SET_AUTHENTICATED",
        SET_UNAUTHENTICATED: "USER.SET_UNAUTHENTICATED",
        SET_USER: "USER.SET_USER",
        LOADING_USER: "USER.LOADING_USER",
        STOP_LOADING_USER: "USER.STOP_LOADING_USER"
    },
    UI: {
        SET_ERRORS: "UI.SET_ERRORS",
        CLEAR_ERRORS: "UI.CLEAR_ERRORS",
        SET_ACTION_DONE: "UI.SET_ACTION_DONE",
        CLEAR_ACTION: "UI.CLEAR_ACTION",
        SEND_EMAIL: "UI.SEND_EMAIL",
        STOP_SEND_EMAIL: "UI.STOP_SEND_EMAIL",
        LOADING_DATA: 'UI.LOADING_DATA',
        STOP_LOADING_DATA: 'UI.STOP_LOADING_DATA',
        SCROLLING: "UI.SCROLLING",
        STOP_SCROLLING: "UI.STOP_SCROLLING",
        BACK_UP: "UI.BACK_UP"
    },
    BOOK: {
        SET_INIT: "BOOK.SET_INIT",
        SET_BOOKS: "BOOK.SET_BOOKS",
        SEARCH: "BOOK.SEARCH",
        SET_FILTER_DATA: "BOOK.SET_FILTER_DATA",
        REFRESH_FILTER: "BOOK.REFRESH_FILTER",
        SORT: "BOOK.SORT",
        SET_SEARCH_DATA: "BOOK.SET_SEARCH_DATA",
        STOP_SEARCH: "BOOK.STOP_SEARCH",
        SET_BOOK: "BOOK.SET_BOOK"
    }
};